blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/luigi-sw/LC.DotNetGenesis/discussions
    about: This issue tracker is not for documentation issues. Please file documentation issues on the Ionic Docs repo.
  - name: 💻 LCSoft DotNetGenesis Support
    url: https://github.com/luigi-sw/LC.DotNetGenesis/discussions
    about: Please ask and answer questions here.
